services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3080
    restart: unless-stopped
